[package]

name = "photometer"
version = "0.0.1"
authors = ["pavlov_dmitry"]


[dependencies]
num = "*"
image = "~0.2.0"

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"

[dependencies.mysql]

git = "https://github.com/blackbeam/rust-mysql-simple.git"
default-features = false
