[package]

name = "photometer"
version = "0.0.1"
authors = ["pavlov_dmitry"]


[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"

[dependencies.mysql]

git = "https://github.com/pavlov-dmitry/rust-mysql-simple.git"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image.git"

[dependencies.num]

git = "https://github.com/rust-lang/num"